### ISSUE TITLE
로컬에서 장고 프로젝트 기본 설정 해두셨나요?

### ISSUE THREAD

**Issue by seonghwan7694** [krome0/universial-kiosk#1]
해두셨다면 푸쉬부탁드리고, 안 해두셨다면 제가 설정해서 창공 시간 전까지 올리겠습니다.

이번 주를 포함해서 창공 수업은 5번이 남았습니다. 굉장히 빠르게 진행된다면 스케쥴은 다음과 같을 것 같습니다.

11/28 - (온라인) '스마트폰', '키오스크' 개발 시작 (= 사실상 장고 개발) & (오프라인) '장애인용 기기' 개발 시작 (= 키패드, QR코드 인식, TTS)
11/30 - (온라인) '스마트폰', '키오스크' 개발 90% 마무리 (UX, UI 어느정도 완성) & (오프라인) '장애인용 기기' 개발 중
12/05 - (온라인) '스마트폰', '키오스크' 개발 100% 마무리 (HTTP 통신을 위한 서버 배포 성공) & (오프라인) '장애인용 기기' 개발 마무리
12/07 - (온라인 & 오프라인) '장애인용 기기' HTTP 통신 or ESPNOW 통신
12/13 7시 이후 - X

대략 읽어보았습니다.

# 작동 방식

## 키오스크
- 키오스크 기기 또한 웹 기반으로 제작 예정

### 기대효과
1. 웹 기반으로 제작하여 Windows, Linux 등 대부분의 환경에서 작동이 가능함
2. 따라서 기존 키오스크를 대체하거나 기존 키오스크에 본 프로젝트의 기능을 추가하는 것을 쉽게 할 수 있음
> 읽어보니, 장고 개발을 진행하면 자연스레 키오스크는 개발되는 것 같습니다.

## 스마트폰
1. QR코드 인식
2. Web 주문 페이지로 이동
3. Web 주문 페이지에서 메뉴 주문
4. 키오스크 or Web 주문 페이지에서 결제

### QR코드 인식
1. 일반적인 QR코드 인식앱으로 가능 (기본 카메라앱, 카카오톡 등등)
2. 인식시 Web 주문 페이지로 이동

### 주문
- 키오스크 주문과 동일하게 웹에서 주문이 가능하게 함
> 읽어보니, 장고 개발을 진행하면 자연스레 스마트폰은 개발되는 것 같습니다.

### 결제
- 모바일에서 카드, 삼성페이, 등으로 결제가 가능하게 함 + 키오스크 기기에서 결제가 가능하게 함
> 이해가 잘 안 가네요. [카카오페이 API](https://developers.kakao.com/docs/latest/ko/kakaopay/single-payment)와 같은걸 사용한다는 것일까요? 제 생각에는 [복잡한 절차](https://m.blog.naver.com/iamport/220963581829)가 존재하기에 결제 기능은 무리이지 않을까 싶습니다.

### 기대효과
1. 키오스크 앞에 사람이 몰리거나 줄이 길어지는 것을 줄일 수 있음
2. 기존 키오스크들은 대부분 휠체어 등 거동이 불편한 사람들을 고려하지 않은 디자인을 가지고 있었음
-> 스마트폰을 사용하여 주문이 가능하므로 거동이 불편해도 스마트폰으로 편리하게 주문이 가능함

## 장애인용 기기
1. QR코드 인식
> 장애인용 기기는 ESP32CAM일까요?
2. 키오스크가 장애인용 기기를 인식
> 통신쪽은 제가 아는게 없어서 '키오스크가 장애인용 기기를 인식'한다는게 뭔지 잘 모르겠네요..
3. 메뉴 항목들을 읽어줌
> [아두이노 TTS 라이브러리](https://github.com/jscrane/TTS)를 사용하는 것일까요? 증폭기가 필요하다는데 음..
4. 키패드로 주문
5. 키오스크에서 결제

### 주문
1. 키오스크에서 음성으로 메뉴 안내
2. 키패드 숫자 조합으로 메뉴 선택
3. ESP-NOW or HTTP 통신으로 숫자 조합 전송 
4. 키오스크 기기가 숫자 조합 받음
5. pyautogui 같은 라이브러리로 키오스크 조작
> 키오스크가 태블릿인가요? ESP8266인가요? C로 구현하려면 [이 라이브러리](https://github.com/arduino-libraries/Mouse)를 이용하면 될 것 같습니다.
6. 결제는 키오스크에서 진행하는 것과 동일하게 진행

### 기대효과
- 기존 키오스크는 음성 안내는 있었지만 터치 스크린으로 작동하는 방식이라 시각장애인은 사용이 거의 불가능했음
-> 키패드를 사용한 장애인용 기기로 시각장애인들도 사용이 가능하게 함

**Comment by krome0** [comment]
> 해두셨다면 푸쉬부탁드리고, 안 해두셨다면 제가 설정해서 창공 시간 전까지 올리겠습니다.

아직 안했습니다 저녁에 돌아가서 제가 하거나 설정해서 커밋해주시면 감사하겠습니다.

> 이번 주를 포함해서 창공 수업은 5번이 남았습니다. 굉장히 빠르게 진행된다면 스케쥴은 다음과 같을 것 같습니다.

> 11/28 - (온라인) '스마트폰', '키오스크' 개발 시작 (= 사실상 장고 개발) & (오프라인) '장애인용 기기' 개발 시작 (= 키패드, QR코드 인식, TTS)
> 11/30 - (온라인) '스마트폰', '키오스크' 개발 90% 마무리 (UX, UI 어느정도 완성) & (오프라인) '장애인용 기기' 개발 중
> 12/05 - (온라인) '스마트폰', '키오스크' 개발 100% 마무리 (HTTP 통신을 위한 서버 배포 성공) & (오프라인) '장애인용 기기' 개발 마무리
> 12/07 - (온라인 & 오프라인) '장애인용 기기' HTTP 통신 or ESPNOW 통신
> 12/13 7시 이후 - X

넵 온라인에서 계속 개발하고 오프라인에서는 장애인용 기기 제작 위주로 하면 될 것 같습니다.

> ### 결제
> - 모바일에서 카드, 삼성페이, 등으로 결제가 가능하게 함 + 키오스크 기기에서 결제가 가능하게 함
> > 이해가 잘 안 가네요. [카카오페이 API](https://developers.kakao.com/docs/latest/ko/kakaopay/single-payment)와 같은걸 사용한다는 것일까요? 제 생각에는 [복잡한 절차](https://m.blog.naver.com/iamport/220963581829)가 존재하기에 결제 기능은 무리이지 않을까 싶습니다.

넵 결제 부분은 일단 버튼만 만들어 놓고 이런식으로 결제가 가능한 컨셉이다 라는것만 보여주는 식으로 제작할 예정이였습니다

> ## 장애인용 기기
> 1. QR코드 인식
> > 장애인용 기기는 ESP32CAM일까요?

넵 ESP32-CAM 사용해서 제작해야할것 같습니다. QR코드 인식 라이브러리도 있는것을 확인했습니다

> 2. 키오스크가 장애인용 기기를 인식
> > 통신쪽은 제가 아는게 없어서 '키오스크가 장애인용 기기를 인식'한다는게 뭔지 잘 모르겠네요..

저도 이걸 어떻게 구현할지 아직 잘 모르겠습니다 우선

플랜A - ESP32-CAM이 QR코드를 인식하면 # 해당 주소로 HTTP 통신으로 장애인용 기기가 스캔했다는 데이터를 보냄

플랜B - 장애인용 기기용 QR코드를 따로 만들어서 이것을 장애인용 기기가 인식하면 키오스크에 연결되어있는 ESP의 MAC주소를 받아 ESP-NOW 통신을 진행함

> 3. 메뉴 항목들을 읽어줌
> > [아두이노 TTS 라이브러리](https://github.com/jscrane/TTS)를 사용하는 것일까요? 증폭기가 필요하다는데 음..

키오스크에서 메뉴항목을 읽어주도록 제작할 예정입니다. 장애인분들이 키오스크 앞에서 장애인용 기기를 사용해 키오스크를 조작하는 방식으로 작동하도록 일단 구상했습니다.

> 5. pyautogui 같은 라이브러리로 키오스크 조작
> > 키오스크가 태블릿인가요? ESP8266인가요? C로 구현하려면 [이 라이브러리](https://github.com/arduino-libraries/Mouse)를 이용하면 될 것 같습니다.

ESP32나 8266은 HID 기기로 인식이 안되는거로 알고 있습니다 따라서 Mouse 라이브러리 사용이 불가능할것 같습니다. 그래서 별도의 프로그램으로 키오스크 조작 등이 필요할것 같습니다
키오스크는 일단은 노트북+모니터 조합으로 전시할것 같습니다.

**Comment by seonghwan7694** [comment]
![image](https://user-images.githubusercontent.com/93508637/204199701-f0568b6c-3c67-47eb-8e46-3edf50553200.png)
처음 PR 날려봐서 그런지 파란색이랑 검은색이랑 이어져있어야된다고 생각하는데 떨어졌네요.. 어쩄든 PR은 잘 되었으니 장고 개발을 시작해봅시다...

please go to #3
