### ISSUE TITLE
사용자 인터페이스(UI)를 결정해야합니다.

### ISSUE THREAD

**Issue by seonghwan7694** [krome0/universial-kiosk#3]
현재 프로젝트 구조는 다음과 같습니다.
```bash
.
├── app
│   ├── admin.py
│   ├── apps.py
│   ├── forms.py
│   ├── __init__.py
│   ├── migrations
│   │   └── __init__.py
│   ├── models.py
│   ├── static
│   │   ├── css
│   │   │   └── main.css
│   │   ├── img
│   │   └── js
│   ├── templates
│   │   └── app
│   ├── tests.py
│   ├── urls.py
│   └── views.py
├── conf
│   ├── asgi.py
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── init.sh
├── manage.py
├── media
├── poetry.lock
├── pyproject.toml
├── README.md
├── static
└── templates
    └── main.html
```
이제 프로젝트의 파일을 어떤 방식으로 구조화할 것인지 결정하고 HTML과 CSS 작업, 장고 프로젝트 설계(urls.py와 views.py 매칭, 물건을 위한 models.py 클래스 구현 등등, 템플릿 html 코딩)를 시작하면 될 것 같습니다.

**Comment by seonghwan7694** [comment]
1. ./templates 내 html 파일
[이걸](https://github.com/krome0/universial-kiosk/blob/main/docs/designs.md) 작업하면 될 것 같습니다.
따로 추가할 파일 없이, main.html으로 작업하면 될 것 같습니다.

1-1. QR코드
> 이슈 없습니다.

1-2. 포장, 1-3. 매장
> 가격이 다른 것일까요? 가격이 다르게 하고싶다면 다음과 같은 방법이 존재할 것 같습니다.
>> 방법 1 : 장고 프로젝트 내에서 가격 조정하기 (저는 어떻게 할지 뾰족한 수가 떠오르지 않습니다. 다만, 매장을 위한 페이지, 포장을 위한 페이지를 따루 두는 방법밖에 안 떠오르네요. 안 좋은 방법이죠...) <br>
>> 방법 2 : 자바스크립트 이용 : 전역 변수로 각각의 버튼에 대한 이벤트 리스너를 두고 특정 버튼이 눌렸다면, DOM 객체를 이용해서 자바스크립트 내부에서 HTML 파일의 내용(이때는 가격이 되겠죠. 기본을 포장가격으로 하고 매장 가격은 500 씩 올린다던지)을 수정하는 방법이 있을 것 같습니다.

2. ./app/templates/app 내 html 파일
html 내에서 다음과 같이 생성하면 물건 리스트가 나옵니다. 물론 CSS 작업을 해야합니다. 이때 반복문을 돌리면 고유하게 id를 설정할 수 있는데, 이를 이용해 JS로 선택한 상품의 합계를 구하면 될 것 같습니다. lists 는 키오스크에서 판매할 물건의 리스트이고, lists는 물건입니다. 각각의 버튼에 대해 이벤트 리스너를 두고 선택된다면 하단에 선택된 메뉴가 JS를 이용해 추가된다던지.. 그런 방식이 가능할 것 같습니다.
```html
{% for element in lists %}
{% endfor %}
```

음.. 더 다 쓰기는 어렵고 오늘 8시나 9시 괜찮다면 깃허브에서 이슈로 회의 진행해도 괜찮을 것 같습니다.

**Comment by seonghwan7694** [comment]
디자인하신 사진 올려주면 그대로 html, css로 옮기겠습니다. 그대로 옮길 예정이니 텍스트 정렬이나 배치? 그런 부분 면밀히 확인하면 좋을 것 같네요. 특정 사진(예를들어 픽토그램, 커피 사진)을 사용한다면 사진도 같이 올려주세요.

이전에 prototype~ 이라고 올린 디렉터리처럼 작업해서 올리겠습니다. 그렇게 하니까 장고 개발할 때 복붙만하면 되니 개발속도가 많이 빨라지더라고요.

**Comment by krome0** [comment]
> 디자인하신 사진 올려주면 그대로 html, css로 옮기겠습니다. 그대로 옮길 예정이니 텍스트 정렬이나 배치? 그런 부분 면밀히 확인하면 좋을 것 같네요. 특정 사진(예를들어 픽토그램, 커피 사진)을 사용한다면 사진도 같이 올려주세요.
> 
> 이전에 prototype~ 이라고 올린 디렉터리처럼 작업해서 올리겠습니다. 그렇게 하니까 장고 개발할 때 복붙만하면 되니 개발속도가 많이 빨라지더라고요.

늦어서 죄송해요 ㅜㅜ 일단 수요일에 작업한 주문 페이지 디자인 깃허브에 커밋했습니다.

**Comment by seonghwan7694** [comment]
넵 오늘 새벽쯤에 작업해서 올리겠습니다.
